name: SmartChests
author: Perotin
main: me.perotin.smartchests.SmartChestsPlugin
version: 1.0
commands:
   smartchests:
      aliases: [sc, smartc, schest, smartchest]
      permission: smartchest.command
      usage: &4Error:&c See /sc help for help!
      description: The main command for SmartChests
